// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

namespace CookApps.BM.TTT.Data
{
    [GeneratorSpecDataResource]
    public static partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {72, 39, 54, 87, 52, 44, 103, 49, 64, 124, 82, 96, 85, 127, 63, 100};
    }
}
