// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.BM.TTT.Data
{

    [GeneratorSpecData]
    public partial class SpecGameConfig
    {
        /// #Menu
        [GeneratorId(nameof(config_key), typeof(string))]
        public string config_key;
        public string config_value;
    }

    [GeneratorSpecData]
    public partial class SpecReward
    {
        [GeneratorId(nameof(id), typeof(int))]
        public int id;
        /// dim=중복
        public int reward_id;
        public global::CookApps.BM.TTT.Data.ItemType item_type;
        public int item_id;
        public long item_count;
    }

    [GeneratorSpecData]
    public partial class SpecConsume
    {
        [GeneratorId(nameof(id), typeof(int))]
        public int id;
        /// dim=중복
        public int consume_id;
        public global::CookApps.BM.TTT.Data.ItemType item_type;
        public int item_id;
        public long item_count;
    }

    [GeneratorSpecData]
    public partial class SpecRouletteItem
    {
        /// #Menu
        [GeneratorId(nameof(id), typeof(int))]
        public int id;
        public global::CookApps.BM.TTT.Data.RouletteType roulette_type;
        public int color_value;
        public global::CookApps.BM.TTT.Data.ItemType reward_type;
        /// 기본 지급시 곱하는 양
        public int item_value;
    }

    [GeneratorSpecData]
    public partial class SpecRouletteSet
    {
        /// #Menu
        [GeneratorId(nameof(id), typeof(int))]
        public int id;
        public int roulette_set_id;
        public int roulette_id;
        public int roulette_space;
        public int roulette_Item;
        public int rate;
    }

    [GeneratorSpecData]
    public partial class SpecUpgradeObject
    {
        /// #Menu
        [GeneratorId(nameof(id), typeof(int))]
        public int id;
        public int map_id;
        public global::CookApps.BM.TTT.Data.UpgradeObjectType object_id;
        public int upgrade_step;
        public long upgrade_cost;
    }
}
