// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.BM.TTT.Data
{

    /// #Menu
    public enum RouletteType
    {
        None = 0,
        Reward = 1,
        Multiply = 2,
        Method = 3,
    }

    public enum ItemType
    {
        None = 0,
        coin = 1,
        energy = 2,
        shield = 3,
    }

    public enum UpgradeObjectType
    {
        None = 0,
        Object1 = 1,
        Object2 = 2,
        Object3 = 3,
        Object4 = 4,
        Object5 = 5,
        Object6 = 6,
        Object7 = 7,
        Object8 = 8,
        Object9 = 9,
        Object10 = 10,
    }
}
