// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.BM.MVPWest
{
    [GeneratorSpecDataManager(EnumSpecDataManagerType.JSON_NET)]
    public partial class SpecDataManager
    {
    }

    [GeneratorSpecDataManager(EnumSpecDataManagerType.JSON_NET | EnumSpecDataManagerType.VALIDATOR)]
    public partial class SpecDataValidManager
    {
    }
}
