// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

namespace CookApps.BM.MVPWest
{
    [GeneratorSpecDataResource]
    public static partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {38, 113, 75, 100, 32, 65, 77, 54, 124, 66, 51, 95, 121, 66, 40, 43};
    }
}
