// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.BM.MVPWest
{

    public enum ConfigValueType
    {
        STRING = 0,
        INT = 1,
        FLOAT = 2,
    }

    public enum ItemType
    {
        Gold = 0,
        Jewel = 1,
    }

    public enum GameItemType
    {
        Dice = 1,
        DiceCount = 2,
        Hammer = 3,
    }

    public enum GameItemActiveType
    {
        Immediate = 0,
        Hold = 1,
        HoldAuto = 2,
    }

    public enum TargetType
    {
        Me = 0,
        Target = 1,
        Random = 2,
        All = 3,
    }

    public enum PerkType
    {
        None = 0,
        Reroll = 1,
        SelectItem = 2,
        GetItem = 4,
        SnakeShield = 5,
    }

    public enum PerkActiveType
    {
        None = 0,
        BeforeMove = 1,
        AfterMove = 2,
    }

    public enum PerkCondType
    {
        None = 0,
        Dice = 1,
    }

    public enum RuleType
    {
        None = 0,
        Item_Refill_Odd_Block = 1,
        Hide_Ladder = 2,
        Hide_Snake = 3,
        Item_Exchange = 4,
        Use_Hammer_Six = 5,
        Character_Pos_Change = 6,
        Item_Refresh = 7,
        Prison = 8,
    }
}
