// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.BM.MVPWest
{

    [GeneratorSpecData]
    public partial class SpecGameConfig
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 키 값
        public string config_key;
        /// 자료형 타입
        public global::CookApps.BM.MVPWest.ConfigValueType config_value_type;
        /// 값
        public string config_value;
    }

    [GeneratorSpecData]
    public partial class SpecLanguage
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 키 값
        public string token_key;
        /// 값
        public string language_en;
    }

    [GeneratorSpecData]
    public partial class SpecCharacter
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 ID
        public CookApps.Obfuscator.ObfuscatorInt character_id;
        /// 퍽 ID
        public CookApps.Obfuscator.ObfuscatorInt perk_id;
        /// 캐릭터 이름 key
        public string character_name_key;
    }

    [GeneratorSpecData]
    public partial class SpecPerk
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 퍽 ID
        public CookApps.Obfuscator.ObfuscatorInt perk_id;
        /// 퍽 조건 타입
        public global::CookApps.BM.MVPWest.PerkCondType perk_cond_type;
        /// 퍽 조건 값
        public CookApps.Obfuscator.ObfuscatorInt perk_cond_value;
        /// 퍽 세부 타입
        public global::CookApps.BM.MVPWest.PerkType perk_type;
        /// 퍽 발동 시점 타입
        public global::CookApps.BM.MVPWest.PerkActiveType perk_active_type;
        /// 퍽 적용 타입
        public global::CookApps.BM.MVPWest.TargetType target_type;
        /// 퍽 적용값
        public CookApps.Obfuscator.ObfuscatorFloat[] perk_value = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorFloat>();
        /// 퍽 이름 키
        public string perk_name_key;
        /// 퍽 설명 키
        public string perk_desc_key;
    }

    [GeneratorSpecData]
    public partial class SpecRule
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 룰 ID
        public CookApps.Obfuscator.ObfuscatorInt rule_id;
        /// 룰 타입
        public global::CookApps.BM.MVPWest.RuleType rule_type;
        /// 룰 이름 키
        public string rule_name_key;
        /// 룰 설명 키
        public string rule_desc_key;
        /// 룰 등장 가능 턴 순서
        public CookApps.Obfuscator.ObfuscatorInt[] appear_turn_order = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorInt>();
        /// 룰 등장 확률
        public CookApps.Obfuscator.ObfuscatorFloat rate;
    }

    [GeneratorSpecData]
    public partial class SpecRuleScenario
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 플레이 횟수
        public CookApps.Obfuscator.ObfuscatorInt play_count;
        /// 지정 룰 ID 리스트
        public CookApps.Obfuscator.ObfuscatorInt[] rule_id_list = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorInt>();
    }

    [GeneratorSpecData]
    public partial class SpecItem
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 아이템 ID
        public CookApps.Obfuscator.ObfuscatorInt item_id;
    }

    [GeneratorSpecData]
    public partial class SpecGameItem
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 게임 아이템 ID
        public CookApps.Obfuscator.ObfuscatorInt game_item_id;
        /// 게임 아이템 이름 키
        public string game_item_name_key;
        /// 게임 아이템 타입
        public global::CookApps.BM.MVPWest.GameItemType game_item_type;
        /// 게임 아이템 발동 타입
        public global::CookApps.BM.MVPWest.GameItemActiveType game_item_active_type;
        /// 게임 아이템 적용 타입
        public global::CookApps.BM.MVPWest.TargetType target_type;
        /// 게임 아이템 적용 값
        public CookApps.Obfuscator.ObfuscatorFloat[] game_item_value = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorFloat>();
    }

    [GeneratorSpecData]
    public partial class SpecStage
    {
        /// 인덱스
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 스테이지 ID
        public CookApps.Obfuscator.ObfuscatorInt stage_id;
        /// 스테이지 그룹 ID
        public CookApps.Obfuscator.ObfuscatorInt stage_group_id;
        /// 스테이지 구성 데이터
        public string stage_content_data;
    }
}
